[paths]
data    = "data"
raw     = "data/raw_pdfs"
meta    = "data/metadata"
proc    = "data/processed"
indexed = "data/index"

[files]
chunks_file = "chunks.db"
chunks_done = "chunks.done"
faiss_index = "faiss.index"
side_car    = "chunk_meta.db"
manifest    = "manifest.json"

[model]
embed_model  = "BAAI/bge-large-en-v1.5"
chunk_size   = 512
overlap_frac = 0.20  # 20%
min_char     = 40
batch        = 8     # adjust to your VRAM/CPU
normalize    = true  # cosine via IP when True
page_break   = "\n\n<<<PAGE_BREAK>>>\n\n"

[search]
fts5_tokenizer = "porter"  # Options: simple, porter, unicode61
min_score      = 0.25      # Bullsh*t cut off score
min_score_fts  = 0.1       # Minimum FTS5 relevance score
